// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_jaccard_coefficients
NumericMatrix find_jaccard_coefficients(NumericMatrix knn_ids);
RcppExport SEXP _tidytof_find_jaccard_coefficients(SEXP knn_idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type knn_ids(knn_idsSEXP);
    rcpp_result_gen = Rcpp::wrap(find_jaccard_coefficients(knn_ids));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidytof_find_jaccard_coefficients", (DL_FUNC) &_tidytof_find_jaccard_coefficients, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidytof(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
